// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA_aoGQ_dq7KtRyRGnSufvVZka9sqZJEgQ',
    appId: '1:149082518541:web:d144b9a7a9cf62570cd144',
    messagingSenderId: '149082518541',
    projectId: 'icodegram-yesun',
    authDomain: 'icodegram-yesun.firebaseapp.com',
    storageBucket: 'icodegram-yesun.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBCzFouIcHhtcM3mFyAvs2U4Dw8QXXbT-4',
    appId: '1:149082518541:android:88eda612a9007a780cd144',
    messagingSenderId: '149082518541',
    projectId: 'icodegram-yesun',
    storageBucket: 'icodegram-yesun.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBitzIa7AOzMrJx9sIzDrekTpo7-CyugnA',
    appId: '1:149082518541:ios:ce780661513c04390cd144',
    messagingSenderId: '149082518541',
    projectId: 'icodegram-yesun',
    storageBucket: 'icodegram-yesun.appspot.com',
    iosBundleId: 'com.example.icodegram',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBitzIa7AOzMrJx9sIzDrekTpo7-CyugnA',
    appId: '1:149082518541:ios:7829c0137a35baf90cd144',
    messagingSenderId: '149082518541',
    projectId: 'icodegram-yesun',
    storageBucket: 'icodegram-yesun.appspot.com',
    iosBundleId: 'com.example.icodegram.RunnerTests',
  );
}
